Part 5
lunulu/test-guru pull request #5
Opened 2022-03-01 11:01 UTC by lunulu

2022-03-01 17:03 UTC, BubuntuClu requested changes

2022-03-01 17:03 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
чем `user` отличается от `users`, кроме числа? не понятно по названию что будет возвращать та или иная ассоциация. поэтому надо переименовать текущую ассоциацию в, допустим, `author`. в этом тебе поможет `class_name` опция

2022-03-01 17:03 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
у тебя две ассоциации с одним именем. это не будет работать. надо задать кастомное имя ассоции

2022-03-01 17:03 UTC, BubuntuClu commented on db/migrate/20220203203118_create_tests.rb
> +      t.references :user, foreign_key: true
нельзя править смерженные миграции. надо убрать изменения котоыре ты внес в этот файл и создать их через отдельную миграцию

2022-03-01 17:21 UTC, lunulu commented
Появилась небольшая проблема. user_id добавляется в самый конец, это как-то можно исправить?

![Снимок экрана 2022-03-01 в 20 21 27](https://user-images.githubusercontent.com/65171793/156217306-ff8ba73b-d4f2-4ed9-b20d-c6685d0feda6.png)

2022-03-02 06:46 UTC, BubuntuClu requested changes

2022-03-02 06:46 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, inverse_of: 'author'
все еще две ассоциации с одним названием
`has_many :tests, through: :test_passages`
`has_many :tests, inverse_of: 'author'`
нужно дать другое имя

2022-03-02 06:55 UTC, lunulu commented
> > Появилась небольшая проблема. user_id добавляется в самый конец, это как-то можно исправить?
> > ![Снимок экрана 2022-03-01 в 20 21 27](https://user-images.githubusercontent.com/65171793/156217306-ff8ba73b-d4f2-4ed9-b20d-c6685d0feda6.png)
> 
> а в чем именно тут проблема? новые столбцы добавляются в конец. чтобы был другой порядок надо пересоздать таблицу

Ну неудобно же, created_at и updated_at очень длинные

2022-03-02 07:02 UTC, lunulu commented on app/models/user.rb
> +  has_many :tests, inverse_of: 'author'
А разве inverse_of не это делает? Все ведь работает вроде

2022-03-02 07:16 UTC, lunulu commented on app/models/user.rb
> +  has_many :tests, inverse_of: 'author'
test = Test.first
test.author работает
![Снимок экрана 2022-03-02 в 10 16 08](https://user-images.githubusercontent.com/65171793/156313213-51f16e3c-1388-42ce-8417-9d545445aabe.png)

2022-03-02 16:01 UTC, merged